# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: disable=line-too-long
# pylint: disable=too-many-lines

from azure.cli.core.aaz import *
import json


@register_command(
    "edge-order address create",
)
class Create(AAZCommand):
    """Create a new address with the specified parameters. Existing address can be updated with this API.

    :example: CreateAddress
        az edge-order address create --name "TestMSAddressName" --location "eastus" --contact-details {contact-name:'Petr Cech',email-list:testemail@microsoft.com,phone:1234567890,phone-extension:} --shipping-address {address-type:'None',city:'San Francisco',company-name:Microsoft,country:US,postal-code:94107,state-or-province:CA,street-address1:'16 TOWNSEND ST',street-address2:'UNIT 1'} --resource-group TestRG
    """

    _aaz_info = {
        "version": "2021-12-01",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.edgeorder/addresses/{}", "2021-12-01"],
        ]
    }

    AZ_SUPPORT_NO_WAIT = True

    def _handler(self, command_args):
        super()._handler(command_args)
        return self.ctx.args.to_serialized_data()
        # return self.build_lro_poller(self._execute_operations, self._output)

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.address_name = AAZStrArg(
            options=["--address-name", "--name", "-n"],
            help="The name of the address Resource within the specified resource group. address names must be between 3 and 24 characters in length and use any alphanumeric and underscore only",
            required=True,
            id_part="name",
        )
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )
        _args_schema.location = AAZResourceLocationArg(
            help="The geo-location where the resource lives",
            required=True,
        )
        _args_schema.contact_details = AAZObjectArg(
            options=["--contact-details", "--contact"],
            help="Contact details for the address",
            required=True,
        )
        _args_schema.shipping_address = AAZObjectArg(
            options=["--shipping-address"],
            help="Shipping details for the address",
        )
        _args_schema.tags = AAZDictArg(
            options=["--tags"],
            help="Resource tags.",
        )

        contact_details = cls._args_schema.contact_details
        contact_details.contact_name = AAZStrArg(
            options=["contact-name", "name"],
            help="Contact name of the person.",
            required=True,
        )
        contact_details.emails = AAZListArg(
            options=["emails"],
            singular_options=["email"],
            help="List of Email-ids to be notified about job progress.",
            required=True,
        )
        contact_details.mobile = AAZStrArg(
            options=["mobile"],
            help="Mobile number of the contact person.",
        )
        contact_details.phone = AAZStrArg(
            options=["phone"],
            help="Phone number of the contact person.",
            required=True,
        )
        contact_details.phone_extension = AAZStrArg(
            options=["phone-extension"],
            help="Phone extension number of the contact person.",
        )

        emails = cls._args_schema.contact_details.emails
        emails.Element = AAZStrArg()

        shipping_address = cls._args_schema.shipping_address
        shipping_address.type = AAZStrArg(
            options=["type"],
            help="Type of address.",
            enum={"Commercial": "Commercial", "None": "None", "Residential": "Residential"},
        )
        shipping_address.city = AAZStrArg(
            options=["city"],
            help="Name of the City.",
        )
        shipping_address.company = AAZStrArg(
            options=["company"],
            help="Name of the company.",
        )
        shipping_address.country = AAZStrArg(
            options=["country"],
            help="Name of the Country.",
            required=True,
        )
        shipping_address.postal_code = AAZStrArg(
            options=["postal-code"],
            help="Postal code.",
        )
        shipping_address.province = AAZStrArg(
            options=["province", "state"],
            help="Name of the State or Province.",
        )
        shipping_address.address1 = AAZStrArg(
            options=["address1"],
            help="Street Address line 1.",
            required=True,
        )
        shipping_address.address2 = AAZStrArg(
            options=["address2"],
            help="Street Address line 2.",
        )
        shipping_address.address3 = AAZStrArg(
            options=["address3"],
            help="Street Address line 3.",
        )
        shipping_address.zip_code = AAZStrArg(
            options=["zip-code"],
            help="Extended Zip Code.",
        )

        tags = cls._args_schema.tags
        tags.Element = AAZStrArg()
        return cls._args_schema

    def _execute_operations(self):
        yield self.CreateAddress(ctx=self.ctx)()

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class CreateAddress(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [202]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )
            if session.http_response.status_code in [200]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EdgeOrder/addresses/{addressName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "PUT"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "addressName", self.ctx.args.address_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2021-12-01",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                typ=AAZObjectType,
            )
            _builder.set_prop("location", AAZStrType, ".location", typ_kwargs={"flags": {"required": True}})
            _builder.set_prop("properties", AAZObjectType, ".", typ_kwargs={"flags": {"required": True, "client_flatten": True}})
            _builder.set_prop("tags", AAZDictType, ".tags")

            properties = _builder.get(".properties")
            if properties is not None:
                properties.set_prop("contactDetails", AAZObjectType, ".contact_details", typ_kwargs={"flags": {"required": True}})
                properties.set_prop("shippingAddress", AAZObjectType, ".shipping_address")

            contact_details = _builder.get(".properties.contactDetails")
            if contact_details is not None:
                contact_details.set_prop("contactName", AAZStrType, ".contact_name", typ_kwargs={"flags": {"required": True}})
                contact_details.set_prop("emailList", AAZListType, ".emails", typ_kwargs={"flags": {"required": True}})
                contact_details.set_prop("mobile", AAZStrType, ".mobile")
                contact_details.set_prop("phone", AAZStrType, ".phone", typ_kwargs={"flags": {"required": True}})
                contact_details.set_prop("phoneExtension", AAZStrType, ".phone_extension")

            email_list = _builder.get(".properties.contactDetails.emailList")
            if email_list is not None:
                email_list.set_elements(AAZStrType, ".")

            shipping_address = _builder.get(".properties.shippingAddress")
            if shipping_address is not None:
                shipping_address.set_prop("addressType", AAZStrType, ".type")
                shipping_address.set_prop("city", AAZStrType, ".city")
                shipping_address.set_prop("companyName", AAZStrType, ".company")
                shipping_address.set_prop("country", AAZStrType, ".country", typ_kwargs={"flags": {"required": True}})
                shipping_address.set_prop("postalCode", AAZStrType, ".postal_code")
                shipping_address.set_prop("stateOrProvince", AAZStrType, ".province")
                shipping_address.set_prop("streetAddress1", AAZStrType, ".address1", typ_kwargs={"flags": {"required": True}})
                shipping_address.set_prop("streetAddress2", AAZStrType, ".address2")
                shipping_address.set_prop("streetAddress3", AAZStrType, ".address3")
                shipping_address.set_prop("zipExtendedCode", AAZStrType, ".zip_code")

            tags = _builder.get(".tags")
            if tags is not None:
                tags.set_elements(AAZStrType, ".")

            return self.serialize_content(_content_value)

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()

            _schema_on_200 = cls._schema_on_200
            _schema_on_200.id = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200.location = AAZStrType(
                flags={"required": True},
            )
            _schema_on_200.name = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200.properties = AAZObjectType(
                flags={"required": True, "client_flatten": True},
            )
            _schema_on_200.system_data = AAZObjectType(
                serialized_name="systemData",
                flags={"read_only": True},
            )
            _schema_on_200.tags = AAZDictType()
            _schema_on_200.type = AAZStrType(
                flags={"read_only": True},
            )

            properties = cls._schema_on_200.properties
            properties.address_validation_status = AAZStrType(
                serialized_name="addressValidationStatus",
                flags={"read_only": True},
            )
            properties.contact_details = AAZObjectType(
                serialized_name="contactDetails",
                flags={"required": True},
            )
            properties.shipping_address = AAZObjectType(
                serialized_name="shippingAddress",
            )

            contact_details = cls._schema_on_200.properties.contact_details
            contact_details.contact_name = AAZStrType(
                serialized_name="contactName",
                flags={"required": True},
            )
            contact_details.email_list = AAZListType(
                serialized_name="emailList",
                flags={"required": True},
            )
            contact_details.mobile = AAZStrType()
            contact_details.phone = AAZStrType(
                flags={"required": True},
            )
            contact_details.phone_extension = AAZStrType(
                serialized_name="phoneExtension",
            )

            email_list = cls._schema_on_200.properties.contact_details.email_list
            email_list.Element = AAZStrType()

            shipping_address = cls._schema_on_200.properties.shipping_address
            shipping_address.address_type = AAZStrType(
                serialized_name="addressType",
            )
            shipping_address.city = AAZStrType()
            shipping_address.company_name = AAZStrType(
                serialized_name="companyName",
            )
            shipping_address.country = AAZStrType(
                flags={"required": True},
            )
            shipping_address.postal_code = AAZStrType(
                serialized_name="postalCode",
            )
            shipping_address.state_or_province = AAZStrType(
                serialized_name="stateOrProvince",
            )
            shipping_address.street_address1 = AAZStrType(
                serialized_name="streetAddress1",
                flags={"required": True},
            )
            shipping_address.street_address2 = AAZStrType(
                serialized_name="streetAddress2",
            )
            shipping_address.street_address3 = AAZStrType(
                serialized_name="streetAddress3",
            )
            shipping_address.zip_extended_code = AAZStrType(
                serialized_name="zipExtendedCode",
            )

            system_data = cls._schema_on_200.system_data
            system_data.created_at = AAZStrType(
                serialized_name="createdAt",
                flags={"read_only": True},
            )
            system_data.created_by = AAZStrType(
                serialized_name="createdBy",
                flags={"read_only": True},
            )
            system_data.created_by_type = AAZStrType(
                serialized_name="createdByType",
                flags={"read_only": True},
            )
            system_data.last_modified_at = AAZStrType(
                serialized_name="lastModifiedAt",
                flags={"read_only": True},
            )
            system_data.last_modified_by = AAZStrType(
                serialized_name="lastModifiedBy",
                flags={"read_only": True},
            )
            system_data.last_modified_by_type = AAZStrType(
                serialized_name="lastModifiedByType",
                flags={"read_only": True},
            )

            tags = cls._schema_on_200.tags
            tags.Element = AAZStrType()

            return cls._schema_on_200


__all__ = ["Create"]
