# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: disable=line-too-long
# pylint: disable=too-many-lines

from azure.cli.core.aaz import *


@register_command(
    "edge-order address list",
)
class List(AAZCommand):
    """List all the addresses available under the given resource group. And List all the addresses available under the subscription.

    :example: ListAddressesAtResourceGroupLevel
        az edge-order address list --resource-group "TestRG"

    :example: ListAddressesAtSubscriptionLevel
        az edge-order address list
    """

    _aaz_info = {
        "version": "2021-12-01",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/providers/microsoft.edgeorder/addresses", "2021-12-01"],
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.edgeorder/addresses", "2021-12-01"],
        ]
    }

    def _handler(self, command_args):
        super()._handler(command_args)
        return self.build_paging(self._execute_operations, self._output)

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.resource_group = AAZResourceGroupNameArg()
        _args_schema.filter = AAZStrArg(
            options=["--filter"],
            help="filter is supported to filter based on shipping address properties. Filter supports only equals operation.",
        )
        _args_schema.skip_token = AAZStrArg(
            options=["--skip-token"],
            help="skipToken is supported on Get list of addresses, which provides the next page in the list of addresses.",
        )
        return cls._args_schema

    def _execute_operations(self):
        condition_0 = has_value(self.ctx.args.resource_group) and has_value(self.ctx.subscription_id)
        condition_1 = has_value(self.ctx.subscription_id) and has_value(self.ctx.args.resource_group) is not True
        if condition_0:
            self.ListAddressesAtResourceGroupLevel(ctx=self.ctx)()
        if condition_1:
            self.ListAddressesAtSubscriptionLevel(ctx=self.ctx)()

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance.value, client_flatten=True)
        next_link = self.deserialize_output(self.ctx.vars.instance.next_link)
        return result, next_link

    class ListAddressesAtResourceGroupLevel(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EdgeOrder/addresses",
                **self.url_parameters
            )

        @property
        def method(self):
            return "GET"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "$filter", self.ctx.args.filter,
                ),
                **self.serialize_query_param(
                    "$skipToken", self.ctx.args.skip_token,
                ),
                **self.serialize_query_param(
                    "api-version", "2021-12-01",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()

            _schema_on_200 = cls._schema_on_200
            _schema_on_200.next_link = AAZStrType(
                serialized_name="nextLink",
            )
            _schema_on_200.value = AAZListType(
                flags={"read_only": True},
            )

            value = cls._schema_on_200.value
            value.Element = AAZObjectType(
                flags={"read_only": True},
            )

            _element = cls._schema_on_200.value.Element
            _element.id = AAZStrType(
                flags={"read_only": True},
            )
            _element.location = AAZStrType(
                flags={"required": True, "read_only": True},
            )
            _element.name = AAZStrType(
                flags={"read_only": True},
            )
            _element.properties = AAZObjectType(
                flags={"required": True, "client_flatten": True, "read_only": True},
            )
            _element.system_data = AAZObjectType(
                serialized_name="systemData",
                flags={"read_only": True},
            )
            _element.tags = AAZDictType(
                flags={"read_only": True},
            )
            _element.type = AAZStrType(
                flags={"read_only": True},
            )

            properties = cls._schema_on_200.value.Element.properties
            properties.address_validation_status = AAZStrType(
                serialized_name="addressValidationStatus",
                flags={"read_only": True},
            )
            properties.contact_details = AAZObjectType(
                serialized_name="contactDetails",
                flags={"required": True, "read_only": True},
            )
            properties.shipping_address = AAZObjectType(
                serialized_name="shippingAddress",
                flags={"read_only": True},
            )

            contact_details = cls._schema_on_200.value.Element.properties.contact_details
            contact_details.contact_name = AAZStrType(
                serialized_name="contactName",
                flags={"required": True, "read_only": True},
            )
            contact_details.email_list = AAZListType(
                serialized_name="emailList",
                flags={"required": True, "read_only": True},
            )
            contact_details.mobile = AAZStrType(
                flags={"read_only": True},
            )
            contact_details.phone = AAZStrType(
                flags={"required": True, "read_only": True},
            )
            contact_details.phone_extension = AAZStrType(
                serialized_name="phoneExtension",
                flags={"read_only": True},
            )

            email_list = cls._schema_on_200.value.Element.properties.contact_details.email_list
            email_list.Element = AAZStrType(
                flags={"read_only": True},
            )

            shipping_address = cls._schema_on_200.value.Element.properties.shipping_address
            shipping_address.address_type = AAZStrType(
                serialized_name="addressType",
                flags={"read_only": True},
            )
            shipping_address.city = AAZStrType(
                flags={"read_only": True},
            )
            shipping_address.company_name = AAZStrType(
                serialized_name="companyName",
                flags={"read_only": True},
            )
            shipping_address.country = AAZStrType(
                flags={"required": True, "read_only": True},
            )
            shipping_address.postal_code = AAZStrType(
                serialized_name="postalCode",
                flags={"read_only": True},
            )
            shipping_address.state_or_province = AAZStrType(
                serialized_name="stateOrProvince",
                flags={"read_only": True},
            )
            shipping_address.street_address1 = AAZStrType(
                serialized_name="streetAddress1",
                flags={"required": True, "read_only": True},
            )
            shipping_address.street_address2 = AAZStrType(
                serialized_name="streetAddress2",
                flags={"read_only": True},
            )
            shipping_address.street_address3 = AAZStrType(
                serialized_name="streetAddress3",
                flags={"read_only": True},
            )
            shipping_address.zip_extended_code = AAZStrType(
                serialized_name="zipExtendedCode",
                flags={"read_only": True},
            )

            system_data = cls._schema_on_200.value.Element.system_data
            system_data.created_at = AAZStrType(
                serialized_name="createdAt",
                flags={"read_only": True},
            )
            system_data.created_by = AAZStrType(
                serialized_name="createdBy",
                flags={"read_only": True},
            )
            system_data.created_by_type = AAZStrType(
                serialized_name="createdByType",
                flags={"read_only": True},
            )
            system_data.last_modified_at = AAZStrType(
                serialized_name="lastModifiedAt",
                flags={"read_only": True},
            )
            system_data.last_modified_by = AAZStrType(
                serialized_name="lastModifiedBy",
                flags={"read_only": True},
            )
            system_data.last_modified_by_type = AAZStrType(
                serialized_name="lastModifiedByType",
                flags={"read_only": True},
            )

            tags = cls._schema_on_200.value.Element.tags
            tags.Element = AAZStrType(
                flags={"read_only": True},
            )

            return cls._schema_on_200

    class ListAddressesAtSubscriptionLevel(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/providers/Microsoft.EdgeOrder/addresses",
                **self.url_parameters
            )

        @property
        def method(self):
            return "GET"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "$filter", self.ctx.args.filter,
                ),
                **self.serialize_query_param(
                    "$skipToken", self.ctx.args.skip_token,
                ),
                **self.serialize_query_param(
                    "api-version", "2021-12-01",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()

            _schema_on_200 = cls._schema_on_200
            _schema_on_200.next_link = AAZStrType(
                serialized_name="nextLink",
            )
            _schema_on_200.value = AAZListType(
                flags={"read_only": True},
            )

            value = cls._schema_on_200.value
            value.Element = AAZObjectType(
                flags={"read_only": True},
            )

            _element = cls._schema_on_200.value.Element
            _element.id = AAZStrType(
                flags={"read_only": True},
            )
            _element.location = AAZStrType(
                flags={"required": True, "read_only": True},
            )
            _element.name = AAZStrType(
                flags={"read_only": True},
            )
            _element.properties = AAZObjectType(
                flags={"required": True, "client_flatten": True, "read_only": True},
            )
            _element.system_data = AAZObjectType(
                serialized_name="systemData",
                flags={"read_only": True},
            )
            _element.tags = AAZDictType(
                flags={"read_only": True},
            )
            _element.type = AAZStrType(
                flags={"read_only": True},
            )

            properties = cls._schema_on_200.value.Element.properties
            properties.address_validation_status = AAZStrType(
                serialized_name="addressValidationStatus",
                flags={"read_only": True},
            )
            properties.contact_details = AAZObjectType(
                serialized_name="contactDetails",
                flags={"required": True, "read_only": True},
            )
            properties.shipping_address = AAZObjectType(
                serialized_name="shippingAddress",
                flags={"read_only": True},
            )

            contact_details = cls._schema_on_200.value.Element.properties.contact_details
            contact_details.contact_name = AAZStrType(
                serialized_name="contactName",
                flags={"required": True, "read_only": True},
            )
            contact_details.email_list = AAZListType(
                serialized_name="emailList",
                flags={"required": True, "read_only": True},
            )
            contact_details.mobile = AAZStrType(
                flags={"read_only": True},
            )
            contact_details.phone = AAZStrType(
                flags={"required": True, "read_only": True},
            )
            contact_details.phone_extension = AAZStrType(
                serialized_name="phoneExtension",
                flags={"read_only": True},
            )

            email_list = cls._schema_on_200.value.Element.properties.contact_details.email_list
            email_list.Element = AAZStrType(
                flags={"read_only": True},
            )

            shipping_address = cls._schema_on_200.value.Element.properties.shipping_address
            shipping_address.address_type = AAZStrType(
                serialized_name="addressType",
                flags={"read_only": True},
            )
            shipping_address.city = AAZStrType(
                flags={"read_only": True},
            )
            shipping_address.company_name = AAZStrType(
                serialized_name="companyName",
                flags={"read_only": True},
            )
            shipping_address.country = AAZStrType(
                flags={"required": True, "read_only": True},
            )
            shipping_address.postal_code = AAZStrType(
                serialized_name="postalCode",
                flags={"read_only": True},
            )
            shipping_address.state_or_province = AAZStrType(
                serialized_name="stateOrProvince",
                flags={"read_only": True},
            )
            shipping_address.street_address1 = AAZStrType(
                serialized_name="streetAddress1",
                flags={"required": True, "read_only": True},
            )
            shipping_address.street_address2 = AAZStrType(
                serialized_name="streetAddress2",
                flags={"read_only": True},
            )
            shipping_address.street_address3 = AAZStrType(
                serialized_name="streetAddress3",
                flags={"read_only": True},
            )
            shipping_address.zip_extended_code = AAZStrType(
                serialized_name="zipExtendedCode",
                flags={"read_only": True},
            )

            system_data = cls._schema_on_200.value.Element.system_data
            system_data.created_at = AAZStrType(
                serialized_name="createdAt",
                flags={"read_only": True},
            )
            system_data.created_by = AAZStrType(
                serialized_name="createdBy",
                flags={"read_only": True},
            )
            system_data.created_by_type = AAZStrType(
                serialized_name="createdByType",
                flags={"read_only": True},
            )
            system_data.last_modified_at = AAZStrType(
                serialized_name="lastModifiedAt",
                flags={"read_only": True},
            )
            system_data.last_modified_by = AAZStrType(
                serialized_name="lastModifiedBy",
                flags={"read_only": True},
            )
            system_data.last_modified_by_type = AAZStrType(
                serialized_name="lastModifiedByType",
                flags={"read_only": True},
            )

            tags = cls._schema_on_200.value.Element.tags
            tags.Element = AAZStrType(
                flags={"read_only": True},
            )

            return cls._schema_on_200


__all__ = ["List"]
