# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: disable=line-too-long
# pylint: disable=too-many-lines

from azure.cli.core.aaz import *


@register_command_group(
    "data-bricks workspace",
)
class __CMDGroup(AAZCommandGroup):
    """Commands to manage databricks workspace.
    """
    pass


__all__ = ["__CMDGroup"]
